[HTTPServeMux.Patterns]
GRPCGateway = "/v1beta1/"
GraphQL = "/graphql"
GraphQLPlayground = "/graphql/playground"

[HTTPServer]
Port = 8080

[GRPCServer]
Port = 8081

[Logger]
Level = "debug"
Development = true
