// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"context"
	"github.com/odsod/gqlgen-example/internal/middleware"
	"github.com/odsod/gqlgen-example/internal/resolver"
)

// Injectors from wire.go:

func Init(ctx context.Context, cfg *Config) (*App, func(), error) {
	logger, cleanup, err := InitLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	inMemory, err := InitInMemoryStorage(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mutation := &resolver.Mutation{
		Storage: inMemory,
		Logger:  logger,
	}
	query := &resolver.Query{
		Storage: inMemory,
		Logger:  logger,
	}
	todo := &resolver.Todo{
		Logger: logger,
	}
	root := &resolver.Root{
		Storage:          inMemory,
		Logger:           logger,
		MutationResolver: mutation,
		QueryResolver:    query,
		TodoResolver:     todo,
	}
	executableSchema := InitExecutableSchema(root)
	userServiceClient, cleanup2, err := InitUserServiceClient(ctx, cfg, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dataloader := &middleware.Dataloader{
		Storage:           inMemory,
		UserServiceClient: userServiceClient,
		Logger:            logger,
	}
	serveMux := InitHTTPServeMux(cfg, logger, executableSchema, dataloader)
	server := InitHTTPServer(serveMux)
	service, err := InitUserService(ctx, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	grpcServer := InitGRPCServer(service)
	app := &App{
		Config:     cfg,
		HTTPServer: server,
		GRPCServer: grpcServer,
		Logger:     logger,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
