// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"context"
	"github.com/odsod/gqlgen-example/internal/dataloader"
	"github.com/odsod/gqlgen-example/internal/resolver"
)

// Injectors from wire.go:

func Init(ctx context.Context, cfg *Config) (*App, func(), error) {
	logger, cleanup, err := InitLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	inMemory, err := InitInMemoryStorage(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mutation := &resolver.Mutation{
		Storage: inMemory,
		Logger:  logger,
	}
	query := &resolver.Query{
		Storage: inMemory,
		Logger:  logger,
	}
	todo := &resolver.Todo{
		Logger: logger,
	}
	root := &resolver.Root{
		Storage:          inMemory,
		Logger:           logger,
		MutationResolver: mutation,
		QueryResolver:    query,
		TodoResolver:     todo,
	}
	executableSchema := InitExecutableSchema(root)
	middleware := &dataloader.Middleware{
		Storage: inMemory,
		Logger:  logger,
	}
	serveMux := InitHTTPServeMux(logger, executableSchema, middleware)
	server := InitHTTPServer(cfg, serveMux)
	app := &App{
		HTTPServer: server,
		Logger:     logger,
	}
	return app, func() {
		cleanup()
	}, nil
}
